version: "3.9"

services:
  api:
    image: api-project
    container_name: api_project
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/api
    tty: true
