version: "3.9"

services:
  api:
    image: devmiguelangel/ms-api
    container_name: ms_api
    build:
      context: .
      dockerfile: compose/api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    tty: true
